/**
 * Shared candidate data — consumed by Pipeline and referenced in jobData.
 * Some candidates here are the same ones listed in job topCandidates.
 * Replace with API calls in production.
 */

export const CANDIDATES = [
  // ── From Job 1: Senior Software Engineer ──
  {
    id: 1,
    name: 'Sarah Johnson',
    email: 'sarah.j@mail.com',
    job: 'Senior Software Engineer',
    score: 94,
    date: 'Feb 12, 2026',
    antiCheat: 'clean',
    status: 'shortlist',
    skills: ['Java', 'Spring Boot', 'Docker'],
  },
  {
    id: 2,
    name: 'Omar Al-Hassan',
    email: 'omar.h@mail.com',
    job: 'Senior Software Engineer',
    score: 91,
    date: 'Feb 10, 2026',
    antiCheat: 'clean',
    status: 'shortlist',
    skills: ['PostgreSQL', 'Microservices'],
  },
  {
    id: 3,
    name: 'Leila Ahmadi',
    email: 'leila.a@mail.com',
    job: 'Senior Software Engineer',
    score: 88,
    date: 'Feb 9, 2026',
    antiCheat: 'flagged',
    status: 'pending',
    skills: ['Java', 'PostgreSQL'],
  },
  {
    id: 4,
    name: 'James Park',
    email: 'james.p@mail.com',
    job: 'Senior Software Engineer',
    score: 86,
    date: 'Feb 8, 2026',
    antiCheat: 'clean',
    status: 'accepted',
    skills: ['Spring Boot', 'Docker'],
  },
  {
    id: 5,
    name: 'Priya Sharma',
    email: 'priya.s@mail.com',
    job: 'Senior Software Engineer',
    score: 83,
    date: 'Feb 7, 2026',
    antiCheat: 'clean',
    status: 'pending',
    skills: ['Java', 'Microservices'],
  },

  // ── From Job 2: Frontend Developer ──
  {
    id: 6,
    name: 'Lina Markovic',
    email: 'lina.m@mail.com',
    job: 'Frontend Developer',
    score: 92,
    date: 'Feb 11, 2026',
    antiCheat: 'clean',
    status: 'accepted',
    skills: ['React', 'TypeScript'],
  },
  {
    id: 7,
    name: 'David Kim',
    email: 'david.k@mail.com',
    job: 'Frontend Developer',
    score: 89,
    date: 'Feb 10, 2026',
    antiCheat: 'clean',
    status: 'shortlist',
    skills: ['CSS', 'Vite'],
  },
  {
    id: 8,
    name: 'Aya Mahmoud',
    email: 'aya.m@mail.com',
    job: 'Frontend Developer',
    score: 85,
    date: 'Feb 9, 2026',
    antiCheat: 'clean',
    status: 'pending',
    skills: ['React', 'CSS'],
  },
  {
    id: 9,
    name: 'Rania Ibrahim',
    email: 'rania.i@mail.com',
    job: 'Frontend Developer',
    score: 83,
    date: 'Feb 8, 2026',
    antiCheat: 'flagged',
    status: 'shortlist',
    skills: ['TypeScript'],
  },
  {
    id: 10,
    name: 'Samuel Carter',
    email: 'sam.c@mail.com',
    job: 'Frontend Developer',
    score: 80,
    date: 'Feb 7, 2026',
    antiCheat: 'clean',
    status: 'pending',
    skills: ['React', 'Vite'],
  },

  // ── From Job 3: UX Designer ──
  {
    id: 11,
    name: 'Elena Volkov',
    email: 'elena.v@mail.com',
    job: 'UX Designer',
    score: 88,
    date: 'Feb 10, 2026',
    antiCheat: 'clean',
    status: 'shortlist',
    skills: ['Figma', 'Prototyping'],
  },
  {
    id: 12,
    name: 'Isabella Rossi',
    email: 'isa.r@mail.com',
    job: 'UX Designer',
    score: 84,
    date: 'Feb 9, 2026',
    antiCheat: 'clean',
    status: 'accepted',
    skills: ['User Research'],
  },
  {
    id: 13,
    name: 'Sofia Martinez',
    email: 'sofia.m@mail.com',
    job: 'UX Designer',
    score: 79,
    date: 'Feb 8, 2026',
    antiCheat: 'clean',
    status: 'pending',
    skills: ['Design Systems'],
  },

  // ── From Job 4: Data Analyst ──
  {
    id: 14,
    name: 'Chen Wei',
    email: 'chen.w@mail.com',
    job: 'Data Analyst',
    score: 86,
    date: 'Feb 11, 2026',
    antiCheat: 'clean',
    status: 'accepted',
    skills: ['SQL', 'Python'],
  },
  {
    id: 15,
    name: 'Hannah Miller',
    email: 'hannah.m@mail.com',
    job: 'Data Analyst',
    score: 82,
    date: 'Feb 10, 2026',
    antiCheat: 'clean',
    status: 'shortlist',
    skills: ['Tableau', 'Excel'],
  },
  {
    id: 16,
    name: 'Raj Patel',
    email: 'raj.p@mail.com',
    job: 'Data Analyst',
    score: 78,
    date: 'Feb 9, 2026',
    antiCheat: 'clean',
    status: 'pending',
    skills: ['Data Modeling'],
  },

  // ── From Job 5: Backend Engineer ──
  {
    id: 17,
    name: 'Layla Farouk',
    email: 'layla.f@mail.com',
    job: 'Backend Engineer',
    score: 96,
    date: 'Jan 15, 2026',
    antiCheat: 'clean',
    status: 'accepted',
    skills: ['Node.js', 'Go', 'Kubernetes'],
  },
  {
    id: 18,
    name: 'Nathan Brooks',
    email: 'nathan.b@mail.com',
    job: 'Backend Engineer',
    score: 93,
    date: 'Jan 14, 2026',
    antiCheat: 'clean',
    status: 'accepted',
    skills: ['REST APIs', 'MongoDB'],
  },
  {
    id: 19,
    name: 'Mohammed Ali',
    email: 'mo.a@mail.com',
    job: 'Backend Engineer',
    score: 91,
    date: 'Jan 12, 2026',
    antiCheat: 'clean',
    status: 'shortlist',
    skills: ['Redis', 'Go'],
  },
  {
    id: 20,
    name: 'Tom Anderson',
    email: 'tom.a@mail.com',
    job: 'Backend Engineer',
    score: 87,
    date: 'Jan 10, 2026',
    antiCheat: 'flagged',
    status: 'shortlist',
    skills: ['Node.js', 'MongoDB'],
  },
  {
    id: 21,
    name: 'Olivia Zhang',
    email: 'olivia.z@mail.com',
    job: 'Backend Engineer',
    score: 85,
    date: 'Jan 8, 2026',
    antiCheat: 'clean',
    status: 'pending',
    skills: ['Kubernetes', 'REST APIs'],
  },

  // ── From Job 6: Product Manager ──
  {
    id: 22,
    name: 'Daniel Park',
    email: 'daniel.p@mail.com',
    job: 'Product Manager',
    score: 90,
    date: 'Feb 14, 2026',
    antiCheat: 'clean',
    status: 'shortlist',
    skills: ['Agile', 'Analytics'],
  },
  {
    id: 23,
    name: 'Amira Hassan',
    email: 'amira.h@mail.com',
    job: 'Product Manager',
    score: 86,
    date: 'Feb 13, 2026',
    antiCheat: 'clean',
    status: 'accepted',
    skills: ['Roadmapping'],
  },
  {
    id: 24,
    name: "Kevin O'Brien",
    email: 'kevin.o@mail.com',
    job: 'Product Manager',
    score: 82,
    date: 'Feb 12, 2026',
    antiCheat: 'clean',
    status: 'pending',
    skills: ['Stakeholder Mgmt'],
  },

  // ── From Job 7: DevOps Engineer ──
  {
    id: 25,
    name: 'Nora Petersen',
    email: 'nora.p@mail.com',
    job: 'DevOps Engineer',
    score: 91,
    date: 'Feb 13, 2026',
    antiCheat: 'clean',
    status: 'accepted',
    skills: ['AWS', 'Docker'],
  },
  {
    id: 26,
    name: 'Tariq Nasser',
    email: 'tariq.n@mail.com',
    job: 'DevOps Engineer',
    score: 87,
    date: 'Feb 12, 2026',
    antiCheat: 'clean',
    status: 'shortlist',
    skills: ['Terraform', 'Linux'],
  },
  {
    id: 27,
    name: 'Lucas Weber',
    email: 'lucas.w@mail.com',
    job: 'DevOps Engineer',
    score: 82,
    date: 'Feb 11, 2026',
    antiCheat: 'clean',
    status: 'pending',
    skills: ['CI/CD'],
  },

  // ── From Job 8: ML Engineer ──
  {
    id: 28,
    name: 'Fatima Al-Rashid',
    email: 'fatima.r@mail.com',
    job: 'ML Engineer',
    score: 96,
    date: 'Feb 12, 2026',
    antiCheat: 'clean',
    status: 'accepted',
    skills: ['PyTorch', 'MLOps'],
  },
  {
    id: 29,
    name: 'Hadi Mansour',
    email: 'hadi.m@mail.com',
    job: 'ML Engineer',
    score: 93,
    date: 'Feb 11, 2026',
    antiCheat: 'clean',
    status: 'shortlist',
    skills: ['TensorFlow', 'Statistics'],
  },
  {
    id: 30,
    name: 'Mark Reed',
    email: 'mark.r@mail.com',
    job: 'ML Engineer',
    score: 89,
    date: 'Feb 10, 2026',
    antiCheat: 'clean',
    status: 'pending',
    skills: ['Python', 'PyTorch'],
  },

  // ── Additional candidates (not in any job's topCandidates) ──
  {
    id: 31,
    name: 'Youssef Hamed',
    email: 'youssef.h@mail.com',
    job: 'Senior Software Engineer',
    score: 77,
    date: 'Feb 6, 2026',
    antiCheat: 'clean',
    status: 'rejected',
    skills: ['Java'],
  },
  {
    id: 32,
    name: 'Ahmed ElSayed',
    email: 'ahmed.e@mail.com',
    job: 'Backend Engineer',
    score: 72,
    date: 'Feb 5, 2026',
    antiCheat: 'critical',
    status: 'rejected',
    skills: ['Node.js'],
  },
  {
    id: 33,
    name: 'Maria Lopez',
    email: 'maria.l@mail.com',
    job: 'Product Manager',
    score: 68,
    date: 'Feb 4, 2026',
    antiCheat: 'clean',
    status: 'rejected',
    skills: ['Agile'],
  },
  {
    id: 34,
    name: 'James Chen',
    email: 'james.c@mail.com',
    job: 'Frontend Developer',
    score: 75,
    date: 'Feb 3, 2026',
    antiCheat: 'clean',
    status: 'rejected',
    skills: ['React'],
  },
  {
    id: 35,
    name: 'Aisha Yusuf',
    email: 'aisha.y@mail.com',
    job: 'UX Designer',
    score: 71,
    date: 'Feb 2, 2026',
    antiCheat: 'flagged',
    status: 'rejected',
    skills: ['Figma'],
  },
  {
    id: 36,
    name: 'Tobias Muller',
    email: 'tobias.m@mail.com',
    job: 'Data Analyst',
    score: 65,
    date: 'Feb 1, 2026',
    antiCheat: 'clean',
    status: 'rejected',
    skills: ['SQL'],
  },
  {
    id: 37,
    name: 'Mei Lin',
    email: 'mei.l@mail.com',
    job: 'ML Engineer',
    score: 81,
    date: 'Jan 30, 2026',
    antiCheat: 'clean',
    status: 'pending',
    skills: ['Python', 'TensorFlow'],
  },
  {
    id: 38,
    name: 'Carlos Rivera',
    email: 'carlos.r@mail.com',
    job: 'DevOps Engineer',
    score: 73,
    date: 'Jan 29, 2026',
    antiCheat: 'critical',
    status: 'rejected',
    skills: ['Docker'],
  },
];

/** Look up a single candidate by id */
export function getCandidateById(id) {
  return CANDIDATES.find((c) => c.id === id) ?? null;
}

/** Get all candidates for a given job title */
export function getCandidatesByJob(jobTitle) {
  return CANDIDATES.filter((c) => c.job === jobTitle);
}
